# Generated by Django 5.2.3 on 2025-06-25 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "texte_saisi",
                    models.TextField(
                        blank=True,
                        help_text="Note médicale saisie manuellement",
                        null=True,
                        verbose_name="Texte saisi",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Fichier audio de la note médicale",
                        null=True,
                        upload_to="observations/audio/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg", "m4a", "webm"]
                            )
                        ],
                        verbose_name="Fichier audio",
                    ),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True,
                        help_text="Transcription automatique de l'audio",
                        null=True,
                        verbose_name="Transcription",
                    ),
                ),
                (
                    "theme_classe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cardio", "Cardiologie"),
                            ("psy", "Psychiatrie"),
                            ("diabete", "Diabète"),
                            ("neuro", "Neurologie"),
                            ("pneumo", "Pneumologie"),
                            ("gastro", "Gastroentérologie"),
                            ("ortho", "Orthopédie"),
                            ("dermato", "Dermatologie"),
                            ("general", "Médecine générale"),
                            ("autre", "Autre"),
                        ],
                        help_text="Classification automatique du thème médical",
                        max_length=20,
                        null=True,
                        verbose_name="Thème classé",
                    ),
                ),
                (
                    "resume",
                    models.TextField(
                        blank=True,
                        help_text="Résumé automatique généré",
                        null=True,
                        verbose_name="Résumé",
                    ),
                ),
                (
                    "entites",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Entités médicales extraites automatiquement",
                        verbose_name="Entités extraites",
                    ),
                ),
                (
                    "traitement_termine",
                    models.BooleanField(
                        default=False, verbose_name="Traitement terminé"
                    ),
                ),
                (
                    "traitement_erreur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Erreur de traitement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="med_assistant.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation",
                "verbose_name_plural": "Observations",
                "ordering": ["-date"],
            },
        ),
    ]
