# Generated by Django 5.2.3 on 2025-06-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_assistant", "0002_observation_model_prediction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("medecin_generaliste", "Médecin généraliste"),
                            ("medecin_specialiste", "Médecin spécialiste"),
                            ("infirmiere", "Infirmière"),
                            ("aide_soignant", "Aide-soignant"),
                            ("sage_femme", "Sage-femme"),
                            ("kinesitherapeute", "Kinésithérapeute"),
                            ("pharmacien", "Pharmacien"),
                            ("psychologue", "Psychologue"),
                            ("administrateur", "Administrateur"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                        verbose_name="Rôle professionnel",
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        blank=True,
                        help_text="Spécialité médicale ou domaine d'expertise",
                        max_length=100,
                        null=True,
                        verbose_name="Spécialité",
                    ),
                ),
                (
                    "etablissement",
                    models.CharField(
                        blank=True,
                        help_text="Hôpital, clinique, cabinet médical...",
                        max_length=200,
                        null=True,
                        verbose_name="Établissement",
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(
                        blank=True,
                        help_text="Numéro RPPS, ADELI ou autre identifiant professionnel",
                        max_length=50,
                        null=True,
                        verbose_name="Numéro d'ordre",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
    ]
